[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Caskaydia Cove Nerd Font"
bold.family = "Caskaydia Cove Nerd Font"
italic.family = "Caskaydia Cove Nerd Font"
bold_italic.family = "Caskaydia Cove Nerd Font"

size = 11.0

[terminal]

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.

